
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cloud-market-place
  username: gopalpatidar
  password: gopalpatidarpg123
  host: localhost

test:
  <<: *default
  database: cloud-market-place
  username: gopalpatidar
  password: gopalpatidarpg123
  host: localhost

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
